name: tmdb
description: "The Movie Database Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.3
  gap: ^3.0.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+3
  riverpod_annotation: ^2.3.5
  routefly: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_test: ^0.1.5
  nock: ^1.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/
